apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhbmrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhbmrt
  template:
    metadata:
      labels:
        app: dhbmrt
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: dhbmrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ee3f906a-4da7-4b46-bb10-819c848cc85a"
        - name: Vless_Path
          value: "/vlok"
        - name: Vmess_UUID
          value: "ee3f906a-4da7-4b46-bb10-819c848cc85a"
        - name: Vmess_Path
          value: "/vmok"
        - name: Share_Path
          value: "/v2link"
